# This is based on the cibuildwheel example at
# https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml
#
# This workflow builds and tests wheels across multiple platforms using
# cibuildwheel and creates the release sdist. Config not specified here can
# be found in pyproject.toml

name: Build and upload wheels

on:
  workflow_dispatch:
  push:
    branches:
      - master
  release:
    types:
      - released
      - prereleased

jobs:

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz
          overwrite: true

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        if: runner.os == 'Linux' && runner.arch == 'X64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_TEST_REQUIRES: hypothesis pytest
          CIBW_TEST_COMMAND: "python {project}/cydoctest.py -v"  # full test command: py.test {project}/test.py -v
          CIBW_SKIP: "pp* cp36-* cp37-*"
          CIBW_ARCHS_LINUX: ${{ runner.arch == 'X64' && 'auto' || 'auto armv7l' }}
          CIBW_TEST_SKIP: "*-win_arm64"
          CIBW_BUILD_FRONTEND: "build"

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          overwrite: true

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        # Deploy releases to pypi.
        if: github.event_name == 'release' && github.event.action == 'released'
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        # Deploy pre-releases to test pypi.
        if: github.event_name == 'release' && github.event.action == 'prereleased'
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
