name: Release

on:
    push:
        tags: ['*']

jobs:
    wheel_non_linux:
        name: Windows & OSX wheels
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, windows-latest]
                python-version: [3.6, 3.7, 3.8, 3.9]
        steps:
        - name: Set up the repository
          uses: actions/checkout@v2
          with:
              submodules: recursive
              fetch-depth: 0
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
              python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install --upgrade --upgrade-strategy eager 'Cython>=0.29.21' wheel twine
            pip freeze
        - name: Build the package
          run: |
              python setup.py bdist_wheel
        - name: Publish on Github
          uses: svenstaro/upload-release-action@v2
          with:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              file: dist/*
              overwrite: true
              file_glob: true
              tag: ${{ github.ref }}
        - name: Publish on Pypi
          env:
            TWINE_USERNAME:   __token__
            TWINE_PASSWORD:   ${{ secrets.PYPI_API_TOKEN }}
          run: |
            twine upload dist/*
    wheel_linux:
        name: Linux wheels
        runs-on: ubuntu-latest
        steps:
        - name: Set up the repository
          uses: actions/checkout@v2
          with:
              submodules: recursive
              fetch-depth: 0
        - name: Build manylinux2014
          uses: RalfG/python-wheels-manylinux-build@v0.3.4
          with:
            python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
            build-requirements: 'cython'
        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install --upgrade twine
            pip freeze
        - name: Publish on Github
          uses: svenstaro/upload-release-action@v2
          with:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              file: dist/*-manylinux*.whl
              overwrite: true
              file_glob: true
              tag: ${{ github.ref }}
        - name: Publish on Pypi
          env:
            TWINE_USERNAME:   __token__
            TWINE_PASSWORD:   ${{ secrets.PYPI_API_TOKEN }}
          run: |
            twine upload dist/*-manylinux*.whl
    sdist:
        name: Source release
        runs-on: ubuntu-latest
        steps:
        - name: Set up the repository
          uses: actions/checkout@v2
          with:
              submodules: recursive
              fetch-depth: 0
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
              python-version: 3.7
        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install --upgrade --upgrade-strategy eager 'Cython>=0.29.21' wheel twine
            pip freeze
        - name: Build the package
          run: |
              python setup.py sdist
        - name: Publish on Github
          uses: svenstaro/upload-release-action@v2
          with:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              file: dist/*
              overwrite: true
              file_glob: true
              tag: ${{ github.ref }}
        - name: Publish on Pypi
          env:
            TWINE_USERNAME:   __token__
            TWINE_PASSWORD:   ${{ secrets.PYPI_API_TOKEN }}
          run: |
            twine upload dist/*
